baseURL = 'https://onrcayci.github.io'
languageCode = 'en-us'
title = 'Onur Cayci'
theme = 'hugo-coder'
defaultcontentlanguage = 'en-us'

paginate = 20

[markup.highlight]
style = 'github-dark'

[params]
    author = 'Onur Cayci'
    info = 'Software Engineer @ Private AI'
    description = 'My personal website and blog'
    keywords = 'blog,software,developer,engineer,engineering,AI,ML,coding,tech'
    since = 2024
    colorScheme = 'auto'
    avatarurl = 'images/avatar.jpg'

    favicon_32 = 'images/icons8-tech-ios-16-16.png'
    favicon_16 = 'images/icons8-tech-ios-16-32.png'

[[params.social]]
    name = 'GitHub'
    icon = 'fa fa-github fa-2x'
    weight = 1
    url = 'https://github.com/onrcayci'

[[params.social]]
    name = 'LinkedIn'
    icon = 'fa fa-linkedin fa-2x'
    weight = 2
    url = 'https://www.linkedin.com/in/onur-cayci'

[[params.social]]
    name = 'Twitter'
    icon = 'fa fa-twitter fa-2x'
    weight = 3
    url = 'https://twitter.com/onrcaycii'

[[params.social]]
    name = 'Instagram'
    icon = 'fa fa-instagram fa-2x'
    weight = 4
    url = 'https://www.instagram.com/softwarewithonur'
    